sudo: required

language: node_js
node_js:
  - 12

branches:
  only:
  - master
  - /./

notifications:
  email:
    recipients:
      - haibui.dev.1996@gmail.com
      - nguyenhoanganh806@gmail.com
      - vunam1218@gmail.com
      - tiger.fsdev@gmail.com 
    on_success: always
    on_failure: always
  slack: 
    rooms:
      - hw3-cicd:4AGydYWVwKwaLFRDHh7CoYRH#build-notifications
    if: branch == master
    on_failure: always
    on_success: always

services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/frontend-test -f ./frontend/Dockerfile.dev ./frontend
  - docker build -t $DOCKER_ID/backend-test -f ./backend/Dockerfile.dev ./backend
script:
  - docker run -e CI=true $DOCKER_ID/frontend-test yarn test
  - docker run -e CI=true $DOCKER_ID/backend-test npm run test
  - docker pull katalonstudio/katalon
  - docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -apiKey=$KATALON_API_KEY -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="./Katalon/Test Suites/TS_RegressionTest"


after_success:
  - echo docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t $DOCKER_ID/backend ./backend
  - docker build -t $DOCKER_ID/frontend ./frontend
  - docker build -t $DOCKER_ID/nginx ./nginx
  - docker push $DOCKER_ID/backend
  - docker push $DOCKER_ID/frontend
  - docker push $DOCKER_ID/nginx

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'hw3-cicd'
  env: 'Hw3cicd-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-076949635368'
  bucket_path: 'hw3-cicd'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
